const state={view:"dashboard",watch:new Set(["SPY","QQQ","NVDA","BTC/USD"])};
const markets=[
 {t:"SPY",n:"S&P 500 ETF",p:"648.21",c:"+0.84%",v:"42.1M"},
 {t:"QQQ",n:"Nasdaq 100 ETF",p:"578.44",c:"+1.12%",v:"31.7M"},
 {t:"NVDA",n:"NVIDIA",p:"184.73",c:"+2.91%",v:"188.3M"},
 {t:"TSLA",n:"Tesla",p:"342.18",c:"-0.63%",v:"76.4M"},
 {t:"AAPL",n:"Apple",p:"241.60",c:"+0.41%",v:"39.8M"},
 {t:"MSFT",n:"Microsoft",p:"512.33",c:"+0.28%",v:"17.2M"},
 {t:"BTC/USD",n:"Bitcoin",p:"112,840",c:"+1.76%",v:"$38.2B"},
 {t:"ETH/USD",n:"Ethereum",p:"4,621",c:"+2.34%",v:"$21.4B"}
];
function spark(i=0){let pts=[];for(let x=0;x<9;x++){let y=17-((Math.sin(x*1.4+i)+Math.cos(x*.7+i)*.7)*5+x*.7);pts.push(`${x*11},${Math.max(2,Math.min(22,y))}`)}return `<svg class="spark" viewBox="0 0 88 24" preserveAspectRatio="none"><polyline points="${pts.join(" ")}" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>`}
function table(rows=markets){return `<table class="table"><thead><tr><th>SYMBOL</th><th>LAST</th><th>CHG</th><th>VOL</th><th>TREND</th></tr></thead><tbody>${rows.map((m,i)=>`<tr><td><span class="ticker">${m.t}</span><br><span class="sub">${m.n}</span></td><td>${m.p}</td><td class="${m.c[0]=='+'?'up':'down'}">${m.c}</td><td class="muted">${m.v}</td><td class="${m.c[0]=='+'?'up':'down'}">${spark(i)}</td></tr>`).join("")}</tbody></table>`}
function dashboard(){return `<section class="hero"><div class="eyebrow">TERMINAL / MVP</div><h1>Market intelligence without the terminal bloat.</h1><p>SPARK TANK is a lightweight, installable market cockpit for fast situational awareness. This build uses local demo data and is structured to accept live providers later.</p><div class="actions"><button class="action" data-go="markets">Open Markets →</button><button class="action" data-go="watchlist">Open Watchlist →</button><button class="action" data-go="signals">Review Signals →</button></div></section>
<div class="grid cols"><div class="card"><div class="eyebrow">S&P 500</div><div class="big">6,481.52</div><div class="up">+0.84%</div></div><div class="card"><div class="eyebrow">NASDAQ</div><div class="big">21,703.88</div><div class="up">+1.12%</div></div><div class="card"><div class="eyebrow">VIX</div><div class="big">15.72</div><div class="down">-3.08%</div></div><div class="card"><div class="eyebrow">10Y</div><div class="big">4.21%</div><div class="amber">+4 bps</div></div></div>
<div class="grid two" style="margin-top:12px"><div class="card"><div class="section-head"><h2>MARKET BOARD</h2><span class="pill">DEMO</span></div>${table(markets.slice(0,6))}</div><div class="card"><div class="section-head"><h2>LIVE SIGNALS</h2><span class="pill">5</span></div>${signalsList()}</div></div>`}
function signalsList(){return `<div class="signal"><span class="dot green"></span><div><b>Momentum expansion</b><div class="muted">Semis leading broad risk-on tape.</div></div></div><div class="signal"><span class="dot amber"></span><div><b>Watch breadth</b><div class="muted">Index gains are concentrated.</div></div></div><div class="signal"><span class="dot cyan"></span><div><b>Crypto correlation</b><div class="muted">BTC strength tracking growth beta.</div></div></div><div class="signal"><span class="dot red"></span><div><b>Rates sensitivity</b><div class="muted">Long-duration names remain exposed.</div></div></div>`}
function marketsView(){return `<div class="section-head"><h2>MARKETS</h2><span class="pill">LOCAL DEMO DATA</span></div><div class="card">${table()}</div>`}
function watchView(){let rows=markets.filter(m=>state.watch.has(m.t));return `<div class="section-head"><h2>WATCHLIST</h2><span class="pill">${rows.length} NAMES</span></div><div class="card">${table(rows)}<div class="note">Tap/hold interaction is intentionally minimal in MVP. Provider-backed alerts and user accounts are planned for the next layer.</div></div>`}
function signalsView(){return `<div class="section-head"><h2>SIGNALS / TAPE READ</h2><span class="pill">MODEL STUBS</span></div><div class="grid two"><div class="card">${signalsList()}<div class="signal"><span class="dot green"></span><div><b>Relative strength</b><div class="muted">NVDA +2.91% vs QQQ +1.12%</div><div class="bar" style="margin-top:7px"><span style="width:82%"></span></div></div></div></div><div class="card"><div class="eyebrow">RISK POSTURE</div><div class="big amber">BALANCED / RISK-ON</div><p class="muted">Demo interpretation only. No investment recommendation is being made.</p><div class="note">Architecture hook: replace the demo signal array in app.js with a normalized provider adapter.</div></div></div>`}
function about(){return `<div class="grid two"><div class="card"><div class="eyebrow">WHAT IS SPARK TANK?</div><h1>Open terminal philosophy.</h1><p class="muted">A small PWA/terminal inspired by professional market workstations, but designed for a phone first. The MVP favors density, speed and composability over decorative dashboards.</p><h2>Stack</h2><p>Static HTML • CSS • Vanilla JS • Web App Manifest • GitHub Pages-ready • zero runtime dependencies.</p></div><div class="card"><div class="eyebrow">ROADMAP</div><div class="signal"><span class="dot green"></span><div><b>01 — MVP shell</b><div class="muted">Complete</div></div></div><div class="signal"><span class="dot amber"></span><div><b>02 — Data adapters</b><div class="muted">Market, macro, news and crypto feeds</div></div></div><div class="signal"><span class="dot cyan"></span><div><b>03 — Personal layer</b><div class="muted">Watchlists, alerts, layouts and sync</div></div></div><div class="signal"><span class="dot"></span><div><b>04 — Intelligence layer</b><div class="muted">Explainable signals and agent workflows</div></div></div></div></div>`}
function render(){let v=state.view;document.getElementById("app").innerHTML=v==="dashboard"?dashboard():v==="markets"?marketsView():v==="watchlist"?watchView():v==="signals"?signalsView():about();document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===v));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{state.view=b.dataset.go;render()})}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});
setInterval(()=>document.getElementById("clock").textContent=new Date().toLocaleTimeString([], {hour12:false}),1000);
render();
